name: Build and Test

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x, 20.x]
        command: ['lint', 'format', 'test', 'build']
    steps:
      - uses: actions/checkout@v4

      - name: Set Up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable --immutable-cache

      - name: Run ${{ matrix.command }}
        run: yarn ${{ matrix.command }}

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        run: yarn test:docker

      - name: Upload coverage reports to Codecov
        if: matrix.command == 'test'
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
